import React from 'react';
/* eslint-disable @next/next/no-img-element -- Gift icons are dynamic TikTok media URLs. */
import { Gift } from '@/types';

export default function GiftCatalogCard({ gift, accent = 'secondary', mappedLabel, previewLabel, testLabel, onPreview, onTest }: { gift: Gift; accent?: 'primary' | 'secondary'; mappedLabel: string; previewLabel: string; testLabel?: string; onPreview: () => void; onTest?: () => void }) {
  const mappedVideo = gift.activeVideo || gift.videos?.[0];
  const primary = accent === 'primary';
  return <article className={`aspect-[9/16] w-full max-w-[210px] mx-auto rounded-2xl overflow-hidden relative group cursor-pointer border border-border-color bg-bg-card backdrop-blur-md glass-shadow transition-all hover:-translate-y-1 ${primary ? 'hover:border-primary' : 'hover:border-secondary'}`} onClick={onPreview}><span className="absolute top-3 right-3 z-10 rounded-full coin-badge px-2 py-0.5 text-xs">⚡ {gift.coins}</span><div className="absolute inset-0 flex items-center justify-center p-4"><img src={gift.icon} alt={gift.name} className="h-18 w-18 object-contain animate-gift-bob" /></div><div className="absolute bottom-0 inset-x-0 p-3 gift-card-gradient text-center"><strong className="block font-header text-sm text-white truncate">{gift.name}</strong><span className={`mt-1 inline-block max-w-full truncate rounded-md px-2 py-0.5 text-[0.62rem] ${mappedVideo ? (primary ? 'bg-primary/10 text-primary' : 'bg-secondary/10 text-secondary') : 'bg-white/5 text-text-muted'}`}>{mappedVideo || mappedLabel}</span></div><div className="absolute inset-0 card-hover-overlay backdrop-blur-xs flex flex-col items-center justify-center gap-3 opacity-0 group-hover:opacity-100 transition-opacity" onClick={(event) => event.stopPropagation()}><button type="button" onClick={onPreview} className="rounded-xl border border-border-color bg-white/10 px-3 py-1.5 text-xs font-bold text-white">{previewLabel}</button>{onTest && <button type="button" onClick={onTest} className={`rounded-xl px-3 py-1.5 text-xs font-bold ${primary ? 'bg-primary text-white' : 'bg-secondary text-black'}`}>{testLabel}</button>}</div></article>;
}
